---

- name: install epel for centos 6
  yum: name={{ rh_epel_6 }} state=present
  when: ansible_distribution_major_version == "6"

- name: install epel for cnetos 7
  yum: name={{ rh_epel_7 }} state=present
  when: ansible_distribution_major_version == "7"


