---
# tasks file for postgresql_install

- name: is master node defined
  fail:
    msg: "master_node need to be defined"
  when: master_node == 'yes' or master_node == 'no'

- name: ensure all the required playbook variables for master
  fail:
    msg: "vatiable {{ item }} is required"
  when: item == '' and master_node == 'yes'
  with_items: 
    - pg_slave
    - pg_app_name
  
- name: ensure all the required playbook variables for slave
  fail:
    msg: "vatiable {{ item }} is required"
  when: item == '' and master_node == 'no'
  with_items: 
    - pg_slave
    - pg_app_name


- name: ensure pg group
  group: name={{ pg_group }} state=present 

- name: ensure pg users
  user: name={{ pg_owner }} group={{ pg_group }} state=present

- import_tasks: epel.yml
  tags: epel

- import_tasks: filesystems.yml
  tags: filesystem

- import_tasks: packages.yml
  tags: packages

- import_tasks: initdb.yml
  tags: initdb
  when: master_node == 'yes'

- import_tasks: firewall.yml
  tags: firewall

- import_tasks: service.yml
  tags: service

- import_tasks: master_node.yml
  when: master_node == 'yes'
  tags: postgres

- import_tasks: service_start.yml
  when: master_node == 'yes'
  tags: postgres

- import_tasks: replica.yml
  when: master_node == 'yes'
  tags: postgres

- import_tasks: slave_node.yml
  tags: postgres 
  when: master_node == 'no' 

- import_tasks: service_start.yml
  when: master_node == 'no'
  tags: postgres